name: KMP library compilation check

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check plugin
        run: ./gradlew -p units-generator build publishToMavenLocal
      - name: Build K/N cache
        run: ./gradlew :units:runCommonizer
      - name: Check runtime
        run: ./gradlew build publishToMavenLocal syncMultiPlatformLibraryDebugFrameworkIosX64
      - name: Go to ios dir
        run: cd sample/ios-app
      - name: Install pods
        run: pod install
      - name: build ios sample
        run: xcodebuild -scheme TestProj -workspace TestProj.xcworkspace -configuration Debug build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
